"""added comments

Revision ID: 7121e511b78c
Revises: 3606d04affb4
Create Date: 2025-03-30 20:33:22.028954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7121e511b78c'
down_revision: Union[str, None] = '3606d04affb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'id',
               existing_type=sa.UUID(),
               comment='Уникальный идентификатор задачи',
               existing_nullable=False)
    op.alter_column('tasks', 'task_text',
               existing_type=sa.VARCHAR(),
               comment='Текст задачи',
               existing_nullable=False)
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активности задачи. True - задача активна. False - задача завершена',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активности задачи. True - задача активна. False - задача завершена',
               existing_nullable=True)
    op.alter_column('tasks', 'task_text',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Текст задачи',
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Уникальный идентификатор задачи',
               existing_nullable=False)
    # ### end Alembic commands ###
